language: python
sudo: false
python:
- '2.7'
install:
- npm install jscs -g
- npm install jshint -g
- npm install
- jscs -V
- jshint -v
- pip install "GitPython>=0.2.0-beta1"
- mkdir -p vendors
script:
- npm run build-min
- npm test
after_script:
- ./dist-update.sh